name: ci-sample-app-nodejs

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Use NodeJS version-${{ matrix.node-verions }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      #- name: Testing
      # run: "npm ci && npm run build --if-present"
    
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
 
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}